name: flex_color_scheme_example
description: Five examples that demonstrate how to use the FlexColorScheme package.
version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flex_color_scheme:
    path: ../

  flutter:
    sdk: flutter

  # Used for launching a WEB URL (by Google flutter.dev).
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # all image assets used by the program.
  assets:
    - assets/images/