name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
      - name: Show Dart SDK version
        run: dart --version
      - name: Show Flutter SDK version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
    
    # Uncomment this step to verify the use of 'dart format' on each commit.
    # - name: Verify formatting
    #   run: dart format --output=none --set-exit-if-changed .

    # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: Test app
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
      
